export type { ScriptCompletionDetail, AdapterCompileInfo } from "./types/service"

export { doHover } from "./service/hover"
export { format } from "./service/format"
export { getDiagnostic } from "./service/diagnostic"
export { findReferences } from "./service/reference"
export { getSignatureHelp } from "./service/signature"
export { findComponentTagRanges } from "./util/qingkuai"
export { rename, prepareRename } from "./service/rename"
export { doComplete } from "./service/complete/completions"
export { findImplementations } from "./service/implementation"
export { codeLens, resolveCodeLens } from "./service/code-lens"
export { getDocumentColor, getColorPresentations } from "./service/color"
export { findDefinitions, findTypeDefinitions } from "./service/definition"
export { resolveEmmetCompletion, resolveScriptBlockCompletion } from "./service/complete/resolve"
